version: '3.1'

services:

  bot:
    image: docker.pkg.github.com/egregors/vldc-bot/bot:latest
    depends_on:
      - mongo
    env_file:
      - ./prod.env
    logging:
        options:
            max-size: "1M"
            max-file: "10"

  mongo:
    image: mongo:4.2.1-bionic
    volumes:
      - /opt/mongo/data/prod_db:/data/db
    env_file:
      - ./prod.env
    logging:
        options:
            max-size: "1M"
            max-file: "10"

