version: '3.1'

services:

  bot:
    image: docker.pkg.github.com/egregors/vldc-bot/bot_dev:dev
    depends_on:
      - mongo
    env_file:
      - ./dev.env
    logging:
        options:
            max-size: "1M"
            max-file: "10"

  mongo:
    image: mongo:4.2.1-bionic
    volumes:
      - /opt/mongo/data/db:/data/db
    env_file:
      - ./dev.env
    logging:
        options:
            max-size: "1M"
            max-file: "10"

